const ADMIN_PASS = "nashadmin";
const DEFAULT_DJS = [
  {name:"DJ 6PaC", login:"6pac", pass:"nashdj", active:true, photo:""},
  {name:"DJ Frank", login:"frank", pass:"frankdj", active:true, photo:""},
  {name:"DJ LAMB3RT", login:"lamb3rt", pass:"lamb3rtdj", active:true, photo:""}
];
const store = {
  get djs(){return JSON.parse(localStorage.getItem('djNashDjs')||JSON.stringify(DEFAULT_DJS))},
  set djs(v){localStorage.setItem('djNashDjs',JSON.stringify(v)); refreshAll()},
  get live(){return JSON.parse(localStorage.getItem('djNashLive')||'{"dj":"DJ 6PaC","event":"Soirée au Nash"}')},
  set live(v){localStorage.setItem('djNashLive',JSON.stringify(v)); refreshAll()},
  get requests(){return JSON.parse(localStorage.getItem('djNashRequests')||'[]')},
  set requests(v){localStorage.setItem('djNashRequests',JSON.stringify(v)); refreshAll()}
};
function $(id){return document.getElementById(id)}
function esc(s){return String(s||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function activeDjs(){return store.djs.filter(d=>d.active)}
function getDj(name){return store.djs.find(d=>d.name===name)||store.djs[0]||DEFAULT_DJS[0]}
function fillDjSelect(id){const el=$(id); if(!el)return; const current=el.value||store.live.dj; el.innerHTML=activeDjs().map(d=>`<option value="${esc(d.name)}">${esc(d.name)}</option>`).join(''); if([...el.options].some(o=>o.value===current)) el.value=current;}
function updateLive(){const l=store.live, dj=getDj(l.dj); ['liveDj','djCurrent'].forEach(id=>$(id)&&($(id).textContent=l.dj)); ['liveEvent','eventCurrent'].forEach(id=>$(id)&&($(id).textContent=l.event)); if($('adminDj')){$('adminDj').value=l.dj;} if($('adminEvent')) $('adminEvent').value=l.event; ['livePhoto','djPhoto'].forEach(id=>{const img=$(id); if(img){img.src=dj.photo||''; img.classList.toggle('hidden',!dj.photo)}})}
function clientToken(){let t=localStorage.getItem('djNashClientToken'); if(!t){t='client-'+Date.now()+'-'+Math.random().toString(36).slice(2); localStorage.setItem('djNashClientToken',t)} return t;}
function addRequest(r){const list=store.requests; list.unshift({...r,id:Date.now(),clientToken:clientToken(),time:new Date().toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'}),played:false,notified:false}); store.requests=list;}
function playClientBell(){try{const ctx=new (window.AudioContext||window.webkitAudioContext)(); const now=ctx.currentTime; [660,880,1180].forEach((freq,i)=>{const osc=ctx.createOscillator(); const gain=ctx.createGain(); osc.type='sine'; osc.frequency.value=freq; gain.gain.setValueAtTime(0.0001,now+i*0.12); gain.gain.exponentialRampToValueAtTime(0.18,now+i*0.12+0.02); gain.gain.exponentialRampToValueAtTime(0.0001,now+i*0.12+0.18); osc.connect(gain); gain.connect(ctx.destination); osc.start(now+i*0.12); osc.stop(now+i*0.12+0.2);});}catch(e){}}
function renderRequests(targetId){const el=$(targetId); if(!el)return; const reqs=store.requests; el.innerHTML=reqs.length?'':'<p class="hint">Aucune demande pour le moment.</p>'; reqs.forEach(r=>{const d=document.createElement('div'); d.className='req '+(r.played?'played':''); d.innerHTML=`<strong>${esc(r.type)}</strong><br><small>${esc(r.time)} • ${esc(r.name||'Client')} ${r.table?'• '+esc(r.table):''}</small><p>${esc(r.message)}</p><div class="req-actions"><button class="btn ghost" data-play="${r.id}">✓ Jouée</button><button class="btn ghost" data-del="${r.id}">Supprimer</button></div>`; el.appendChild(d);}); el.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{store.requests=store.requests.map(r=>r.id==b.dataset.play?{...r,played:true,playedAt:new Date().toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'}),notify:true}:r)}); el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{store.requests=store.requests.filter(r=>r.id!=b.dataset.del)});}
function renderDjList(){const el=$('djManager'); if(!el)return; el.innerHTML=store.djs.map((d,i)=>`<div class="djrow"><div>${d.photo?`<img src="${d.photo}" class="avatar">`:''}<b>${esc(d.name)}</b><small>${esc(d.login)} • ${d.active?'Actif':'Désactivé'}</small></div><div><button class="btn ghost" data-edit="${i}">Modifier</button><button class="btn ghost" data-toggle="${i}">${d.active?'Désactiver':'Activer'}</button><button class="btn ghost" data-del-dj="${i}">Supprimer</button></div></div>`).join(''); el.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{let a=store.djs; a[b.dataset.toggle].active=!a[b.dataset.toggle].active; store.djs=a;}); el.querySelectorAll('[data-del-dj]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer ce DJ?')){let a=store.djs; a.splice(b.dataset.delDj,1); store.djs=a;}}); el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>loadDjForm(+b.dataset.edit));}
function loadDjForm(i){const d=store.djs[i]; $('djIndex').value=i; $('newDjName').value=d.name; $('newDjLogin').value=d.login; $('newDjPass').value=d.pass; $('newDjActive').checked=d.active; $('photoPreview').src=d.photo||''; $('photoPreview').classList.toggle('hidden',!d.photo);}
function readPhoto(input, cb){const f=input.files&&input.files[0]; if(!f){cb(null);return} const r=new FileReader(); r.onload=()=>cb(r.result); r.readAsDataURL(f);}

function renderClientRequests(){const el=$('clientRequests'); if(!el)return; const mine=store.requests.filter(r=>r.clientToken===clientToken()); el.innerHTML=mine.length?'':'<p class="hint">Tes demandes apparaîtront ici après l’envoi.</p>'; mine.forEach(r=>{const d=document.createElement('div'); d.className='req '+(r.played?'played spotlight':''); d.innerHTML=`<strong>${r.played?'🎉 Ça joue maintenant':'⏳ En attente'}</strong><br><small>${esc(r.time)} ${r.playedAt?'• Jouée à '+esc(r.playedAt):''}</small><p>${esc(r.message)}</p>`; el.appendChild(d);}); const toNotify=mine.filter(r=>r.played&&r.notify&&!r.notified); if(toNotify.length && localStorage.getItem('djNashSoundOk')==='yes'){playClientBell(); store.requests=store.requests.map(r=>toNotify.some(n=>n.id===r.id)?{...r,notified:true}:r);} }
function initClient(){updateLive(); renderClientRequests(); $('enableClientSound')?.addEventListener('click',()=>{localStorage.setItem('djNashSoundOk','yes'); playClientBell(); $('status').textContent='Sonnerie activée ✅';}); $('requestForm')?.addEventListener('submit',e=>{e.preventDefault(); addRequest({name:$('clientName').value,type:$('requestType').value,table:$('tableNumber').value,message:$('message').value}); $('status').textContent='Demande envoyée au DJ ✅'; e.target.reset(); renderClientRequests();});}
function initDj(){fillDjSelect('djName'); updateLive(); renderRequests('requestsList'); $('djLogin')?.addEventListener('submit',e=>{e.preventDefault(); const djName=$('djName').value, pass=$('djPass').value; const dj=getDj(djName); if(!dj||dj.pass!==pass){alert('Mot de passe incorrect'); return;} store.live={...store.live,dj:dj.name}; alert(`${dj.name} est maintenant en direct`);}); $('clearPlayed')?.addEventListener('click',()=>{store.requests=store.requests.filter(r=>!r.played)});}
function initAdmin(){fillDjSelect('adminDj'); updateLive(); renderRequests('adminRequests'); renderDjList(); $('adminLogin')?.addEventListener('submit',e=>{e.preventDefault(); if($('adminPass').value!==ADMIN_PASS){alert('Mot de passe admin incorrect'); return;} $('adminPanel').classList.remove('hidden');}); $('saveLive')?.addEventListener('click',()=>{store.live={dj:$('adminDj').value,event:$('adminEvent').value||'Soirée au Nash'}; alert('Soirée mise en direct');}); $('djPhotoInput')?.addEventListener('change',e=>readPhoto(e.target,data=>{if(data){$('photoPreview').src=data;$('photoPreview').classList.remove('hidden')}})); $('djForm')?.addEventListener('submit',e=>{e.preventDefault(); readPhoto($('djPhotoInput'),data=>{let a=store.djs; const idx=$('djIndex').value; const existing=idx!==''?a[+idx]:{}; const obj={name:$('newDjName').value.trim(), login:$('newDjLogin').value.trim(), pass:$('newDjPass').value, active:$('newDjActive').checked, photo:data||existing.photo||''}; if(!obj.name||!obj.login||!obj.pass){alert('Remplis nom, identifiant et mot de passe');return;} if(idx==='') a.push(obj); else a[+idx]=obj; store.djs=a; e.target.reset(); $('djIndex').value=''; $('photoPreview').classList.add('hidden');});}); $('resetDjForm')?.addEventListener('click',()=>{$('djForm').reset(); $('djIndex').value=''; $('photoPreview').classList.add('hidden');});}
function refreshAll(){fillDjSelect('adminDj'); fillDjSelect('djName'); updateLive(); renderRequests('requestsList'); renderRequests('adminRequests'); renderClientRequests(); renderDjList();}
window.addEventListener('storage',refreshAll);
const page=document.body.dataset.page; if(page==='client')initClient(); if(page==='dj')initDj(); if(page==='admin')initAdmin();
