// NASH DJ QR 1.0 FINAL
// IMPORTANT: remplace le texte ci-dessous par ton URL Google Apps Script Web App qui finit par /exec
const BACKEND_URL = "https://script.google.com/macros/s/AKfycbyfJnt2TfmX0CsNvdyPjPLvwlraCfjTJ0rjKCkcuCh4ulwbX-3palXHqWZ3DDvqoS5_og/exec";

const DEFAULT_STATE={liveDj:"6pac",eventName:"Soirée au Nash",eventDesc:"Scanne, écris ta demande, et le DJ la reçoit.",posterUrl:"",djs:[{id:"6pac",name:"DJ 6PaC",pass:"nashdj",photo:""},{id:"frank",name:"DJ Frank",pass:"frankdj",photo:""},{id:"lamb3rt",name:"DJ LAMB3RT",pass:"lamb3rtdj",photo:""}],requests:[]};
function localGet(){return JSON.parse(localStorage.getItem("nashDjQrState")||JSON.stringify(DEFAULT_STATE))}function localSet(s){localStorage.setItem("nashDjQrState",JSON.stringify(s))}
function api(action,data={}){return new Promise((resolve,reject)=>{if(!BACKEND_URL||BACKEND_URL.includes("COLLE_TON_URL")){const s=localGet();if(action==="getState")return resolve(s);if(action==="saveState"){localSet(data.state);return resolve({ok:true})}if(action==="addRequest"){const req={id:Date.now().toString(),clientName:data.clientName||"",type:data.type||"Demande spéciale",message:data.message||"",status:"new",time:new Date().toLocaleString("fr-CA")};s.requests.unshift(req);localSet(s);return resolve({ok:true,request:req})}if(action==="markPlayed"){const req=s.requests.find(r=>r.id===data.id);if(req)req.status="played";localSet(s);return resolve({ok:true})}if(action==="deleteRequest"){s.requests=s.requests.filter(r=>r.id!==data.id);localSet(s);return resolve({ok:true})}}const cb="nashDjQrCb_"+Date.now()+"_"+Math.floor(Math.random()*999999);window[cb]=(response)=>{delete window[cb];script.remove();resolve(response)};const params=new URLSearchParams({action,callback:cb,payload:JSON.stringify(data)});const script=document.createElement("script");script.src=BACKEND_URL+"?"+params.toString();script.onerror=()=>{delete window[cb];script.remove();reject(new Error("Erreur de connexion backend"))};document.body.appendChild(script)})}
async function getState(){return await api("getState")}async function saveState(state){return await api("saveState",{state})}function setBg(el,url){if(!el)return;el.style.backgroundImage=url?`url("${url}")`:""}
async function renderLiveHeader(){const state=await getState();const dj=(state.djs||DEFAULT_STATE.djs).find(d=>d.id===state.liveDj)||DEFAULT_STATE.djs[0];if(document.getElementById("liveDj"))document.getElementById("liveDj").textContent=dj.name;if(document.getElementById("eventName"))document.getElementById("eventName").textContent=state.eventName||"Soirée au Nash";if(document.getElementById("eventDesc"))document.getElementById("eventDesc").textContent=state.eventDesc||"Scanne, écris ta demande, et le DJ la reçoit.";setBg(document.getElementById("djPhoto"),dj.photo);const posterBox=document.getElementById("eventPosterBox"),poster=document.getElementById("eventPoster");if(posterBox&&poster&&state.posterUrl){poster.src=state.posterUrl;posterBox.classList.remove("hidden")}return state}
async function startClientPage(){await renderLiveHeader();const form=document.getElementById("requestForm");if(!form)return;form.addEventListener("submit",async e=>{e.preventDefault();const button=form.querySelector("button"),status=document.getElementById("statusMsg");button.disabled=true;button.textContent="Envoi...";status.textContent="";try{const res=await api("addRequest",{clientName:document.getElementById("clientName").value,type:document.getElementById("requestType").value,message:document.getElementById("requestMsg").value});if(res&&res.ok===false)status.textContent="Erreur d'envoi. Réessaie.";else{status.textContent="Demande envoyée au DJ ✅";form.reset()}}catch(err){status.textContent="Erreur d'envoi. Vérifie la connexion."}button.disabled=false;button.textContent="Envoyer au DJ"})}
let currentDj=null,djRefreshTimer=null;function startDjPage(){}async function djLogin(){const state=await getState();const user=document.getElementById("djUser").value.trim().toLowerCase(),pass=document.getElementById("djPass").value;const dj=(state.djs||[]).find(d=>d.id===user&&d.pass===pass);if(!dj){document.getElementById("loginMsg").textContent="Accès refusé";return}currentDj=dj;document.getElementById("loginBox").classList.add("hidden");document.getElementById("djPanel").classList.remove("hidden");document.getElementById("djNameTitle").textContent=dj.name;document.getElementById("photoUrl").value=dj.photo||"";setBg(document.getElementById("profilePreview"),dj.photo);await loadRequests();if(djRefreshTimer)clearInterval(djRefreshTimer);djRefreshTimer=setInterval(loadRequests,5000)}
async function saveDjPhoto(){const state=await getState();const photo=document.getElementById("photoUrl").value.trim();const dj=state.djs.find(d=>d.id===currentDj.id);dj.photo=photo;currentDj.photo=photo;await saveState(state);setBg(document.getElementById("profilePreview"),photo);alert("Photo sauvegardée partout ✅")}
async function loadRequests(){const state=await getState();const box=document.getElementById("requestsList");if(!box)return;box.innerHTML="";const requests=state.requests||[];if(!requests.length){box.innerHTML='<p class="hint">Aucune demande pour l’instant.</p>';return}requests.forEach(r=>{const div=document.createElement("div");div.className="request";div.innerHTML=`<b>${escapeHtml(r.clientName||"Client")}</b><br>${escapeHtml(r.type||"Demande spéciale")}<br>${escapeHtml(r.message||"")}<br><small>${escapeHtml(r.time||"")} • Statut: ${escapeHtml(r.status||"new")}</small><div class="requestActions"><button class="small played" onclick="markPlayed('${r.id}')">Jouée ✅</button><button class="small danger" onclick="deleteRequest('${r.id}')">Supprimer 🗑️</button></div>`;box.appendChild(div)})}
async function markPlayed(id){await api("markPlayed",{id});await loadRequests()}async function deleteRequest(id){await api("deleteRequest",{id});await loadRequests()}function startAdminPage(){}async function adminLogin(){const pass=document.getElementById("adminPass").value;if(pass!=="nashadmin"){document.getElementById("adminMsg").textContent="Accès refusé";return}document.getElementById("adminLoginBox").classList.add("hidden");document.getElementById("adminPanel").classList.remove("hidden");await loadAdmin()}
async function loadAdmin(){const state=await getState();const sel=document.getElementById("liveDjSelect");sel.innerHTML="";(state.djs||[]).forEach(d=>{const opt=document.createElement("option");opt.value=d.id;opt.textContent=d.name;if(d.id===state.liveDj)opt.selected=true;sel.appendChild(opt)});document.getElementById("eventInput").value=state.eventName||"";document.getElementById("descInput").value=state.eventDesc||"";document.getElementById("posterInput").value=state.posterUrl||"";await loadDjs()}
async function saveLiveSettings(){const state=await getState();state.liveDj=document.getElementById("liveDjSelect").value;state.eventName=document.getElementById("eventInput").value;state.eventDesc=document.getElementById("descInput").value;state.posterUrl=document.getElementById("posterInput").value;await saveState(state);alert("Mise en direct sauvegardée ✅")}
async function createDj(){const state=await getState();const name=document.getElementById("newDjName").value.trim(),id=document.getElementById("newDjUser").value.trim().toLowerCase(),pass=document.getElementById("newDjPass").value.trim(),photo=document.getElementById("newDjPhoto").value.trim();if(!name||!id||!pass){alert("Nom, identifiant et mot de passe obligatoires");return}if((state.djs||[]).some(d=>d.id===id)){alert("Cet identifiant existe déjà.");return}state.djs.push({id,name,pass,photo});await saveState(state);alert("DJ créé ✅");await loadAdmin()}
async function loadDjs(){const state=await getState();const box=document.getElementById("djList");if(!box)return;box.innerHTML="";(state.djs||[]).forEach(d=>{const div=document.createElement("div");div.className="djrow";div.innerHTML=`<b>${escapeHtml(d.name)}</b><br>Identifiant: ${escapeHtml(d.id)}<br>${d.photo?"Photo: OK":"Photo: vide"}`;box.appendChild(div)})}
async function loadAdminRequests(){const state=await getState();const box=document.getElementById("adminRequestsList");if(!box)return;box.innerHTML="";(state.requests||[]).forEach(r=>{const div=document.createElement("div");div.className="request";div.innerHTML=`<b>${escapeHtml(r.clientName||"Client")}</b><br>${escapeHtml(r.type||"")}<br>${escapeHtml(r.message||"")}<br><small>${escapeHtml(r.time||"")} • ${escapeHtml(r.status||"new")}</small>`;box.appendChild(div)})}
function escapeHtml(str){return String(str).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
